### PR TITLE
Add support to run in docker

### PR DESCRIPTION
**Pull request by denbeigh2000**
This adds some basic support for building and running in docker, which I'm using to run my own deployment. I've also added a couple of lines on building and invoking in the README.

### CODE REVIEW

**Comment by denbeigh2000** [comment]
Cool bot!

**Comment by sb0** [comment]
Awesome keep me posted on Docker progress. I'm currently going deep with Docker and Kubernetes right now for DevOps job.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by denbeigh2000** [comment]
There shouldn't be anything else you need to do, I've built and deployed my own container using this revision.

k8s is not in my scope here, but no ports are exposed so it should be pretty trivial for you to write a chart for it if you'd like to.

**Comment by reaganmcf** [comment]
Sorry for being late on this, looks good to me! Thanks for contributing 😀

**Pull request merged**
